Summary: Common Desktop Applications
Description: Common Desktop Applications
Name: common-desktop-applications
Packages:
- weston-clients
- emotion
#- econnman
#- bluetooth-agent
- org.tizen.calculator
- elementary-tools
- evas-examples
- emotion-examples
